name: Deploy Supabase Functions
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - name: Supabase Login
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: supabase --version
      - name: Set Secrets
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          AMADEUS_ENV: ${{ secrets.AMADEUS_ENV }}
        run: |
          supabase functions secrets set AMADEUS_API_KEY="$AMADEUS_API_KEY" --project-ref "$SUPABASE_PROJECT_REF"
          supabase functions secrets set AMADEUS_API_SECRET="$AMADEUS_API_SECRET" --project-ref "$SUPABASE_PROJECT_REF"
          supabase functions secrets set AMADEUS_ENV="$AMADEUS_ENV" --project-ref "$SUPABASE_PROJECT_REF"
      - name: Deploy Function
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: supabase functions deploy amadeus-flight-search --project-ref "$SUPABASE_PROJECT_REF"
